## Analise de Saude Mental

In [125]:
import os
import pandas as pd
import numpy as np
#import warnings
import warnings
warnings.filterwarnings('ignore')
# Get the current working directory
cwd = os.getcwd()

# Print the current working directory
print("Current working directory: {0}".format(cwd))

Current working directory: /Users/luiz.superti/Documents/GitHub/general

In [126]:
# Change the current working directory
os.chdir('/Users/luiz.superti/Documents/GitHub/general/')

# Print the current working directory
print("Current working directory: {0}".format(os.getcwd()))

Current working directory: /Users/luiz.superti/Documents/GitHub/general

## 1. Import data

In [127]:
ttable_sm = pd.read_csv('tall_table_saude_mental_completa.csv')
ttable_alice = pd.read_csv('tall_table_all_members_stat.csv')

## 2. Sanitization

In [128]:
# Delete program_members
ttable_sm_clean = ttable_sm.dropna(subset = 'program_name')

### 2.1. Ajustar etapa 0, primeiro e segundo mes

In [129]:
# Delete na program members
ttable_sm_step0 = ttable_sm_clean[ttable_sm_clean['month_ord_on_program']<=2]
ttable_sm_step0['cancel_step0'] = np.where(ttable_sm_step0['alice_canceled_at'].notna(), 1,0)

ttable_sm_step0 = ttable_sm_step0[['calendar_date',
                                    'member_internal_code',
                                    'month_ord_on_program',
                                    'program_name',
                                    'alice_member_stat_on_mth',
                                    'current_medico_gestor',
                                    'current_sex',
                                    'current_gender',
                                    'member_age',
                                    'current_city',
                                    'current_state',
                                    'is_b2b',
                                    'alice_employee_or_dependent',
                                    'is_tagged_pericia',
                                    'alice_member_since',
                                    'alice_canceled_at',
                                    'cancel_step0',
                                    'psico_qt_consultas',
                                    'psico_qt_encaminhamentos',
                                    'psiqui_qt_consultas',
                                    'psiqui_qt_encaminhamentos',
                                    'is_part_of_trilha_mindfulness',
                                    'is_part_of_trilha_psicoeduc',  
                                    'trilha_mindfulness_stat_mth',
                                    'trilha_psicoeduc_stat_mth',
                                    'custo_evento_consultas_psico', 'custo_evento_consultas_psiqui',
                                    'care_cost_tot_consultas_psico', 'care_cost_tot_consultas_psiqui',
                                    'psiqui_is_presential_pp',
                                    'psiqui_has_prescription_pp',
                                    'psico_comparecimento_pp',
                                    'psico_in_alice_net_pp',
                                    'medicines',
                                    'ult_gad7_valor', 
                                    'dias_desde_ult_medicao_gad7',
                                    'last_medicao_gad7_posicao_total', 
                                    'ult_phq9_valor', 
                                    'dias_desde_ult_medicao_phq9',
                                    'last_medicao_phq9_posicao_total']]

2.1.1. Aderencia a trilha (TdS)

In [130]:
#TdS aderente a trilha
ttable_sm_step0['adherent_tds_trilha']=0

#Ansiedades
ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade LEVE') & 
                        (ttable_sm_step0['is_part_of_trilha_mindfulness'] == 1) & 
                        (ttable_sm_step0['is_part_of_trilha_psicoeduc'] == 1), 'adherent_tds_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade LEVE COM histórico de abuso/ disf.sexual') & 
                        (ttable_sm_step0['is_part_of_trilha_mindfulness'] == 1) & 
                        (ttable_sm_step0['is_part_of_trilha_psicoeduc'] == 1), 'adherent_tds_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade LEVE COM histórico de abuso/aborto') & 
                        (ttable_sm_step0['is_part_of_trilha_mindfulness'] == 1) & 
                        (ttable_sm_step0['is_part_of_trilha_psicoeduc'] == 1), 'adherent_tds_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade MODERADA SEM prejuízo') & 
                        (ttable_sm_step0['is_part_of_trilha_psicoeduc'] == 1), 'adherent_tds_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade MODERADA COM prejuízo') & 
                        (ttable_sm_step0['is_part_of_trilha_psicoeduc'] == 1), 'adherent_tds_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade GRAVE') & 
                        (ttable_sm_step0['is_part_of_trilha_psicoeduc'] == 1), 'adherent_tds_trilha'] = 1

#DEPRESSAO
ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Depressão LEVE') & 
                        (ttable_sm_step0['is_part_of_trilha_mindfulness'] == 1), 'adherent_tds_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Depressão LEVE COM histórico de abuso/ disf.sexual'), 'adherent_tds_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Depressão MODERADA SEM prejuízo'), 'adherent_tds_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Depressão MODERADA COM prejuízo'), 'adherent_tds_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Depressão GRAVE'), 'adherent_tds_trilha'] = 1


#Misto
ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Misto LEVE (ansiedade e depressão)'), 'adherent_tds_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Misto MODERADO (ansiedade e depressão) SEM prejuízo'), 'adherent_tds_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Misto MODERADO (ansiedade e depressão) COM prejuízo'), 'adherent_tds_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Misto GRAVE (ansiedade e depressão)'), 'adherent_tds_trilha'] = 1


#Transtornos tipo 1 & 2
ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Transtorno Tipo 1'), 'adherent_tds_trilha'] = 1
ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Transtorno Tipo 2'), 'adherent_tds_trilha'] = 1

2.1.2. Aderencia a gad (TdS)

In [131]:
#Tds aderente ao gad
ttable_sm_step0['adherent_tds_gad_phq']=0

ttable_sm_step0.loc[ttable_sm_step0['ult_gad7_valor'].notna(), 'adherent_tds_gad_phq'] = 1
ttable_sm_step0.loc[ttable_sm_step0['ult_phq9_valor'].notna(), 'adherent_tds_gad_phq'] = 1

2.1.3. Aderencia a psicologo

In [132]:
#TdS aderente a psicologo
ttable_sm_step0['adherent_tds_psico']=0

ttable_sm_step0 = ttable_sm_step0.merge(ttable_sm_step0.groupby(['member_internal_code', 'program_name'])['psico_qt_encaminhamentos'].sum().rename('psico_encam_tot'),
                                                            how = 'inner',
                                                            left_on = ['member_internal_code', 'program_name'], right_index = True)
ttable_sm_step0 = ttable_sm_step0.merge(ttable_sm_step0.groupby(['member_internal_code', 'program_name'])['psico_qt_consultas'].sum().rename('psico_consul_tot'),
                                                            how = 'inner',
                                                            left_on = ['member_internal_code', 'program_name'], right_index = True)
                                                            
#Ansiedades
ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade LEVE'), 'adherent_tds_psico'] = 1
ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade LEVE') & 
                    (ttable_sm_step0['psico_encam_tot'] > 0) & 
                    (ttable_sm_step0['psico_consul_tot'] <= 10), 'adherent_tds_psico'] = 0



ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade LEVE COM histórico de abuso/ disf.sexual') & 
                    (ttable_sm_step0['psico_encam_tot'] > 0) & 
                    (ttable_sm_step0['psico_consul_tot'] <= 10), 'adherent_tds_psico'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade LEVE COM histórico de abuso/aborto') & 
                    (ttable_sm_step0['psico_encam_tot'] > 0) & 
                    (ttable_sm_step0['psico_consul_tot'] <= 10), 'adherent_tds_psico'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade MODERADA SEM prejuízo') & 
                    (ttable_sm_step0['psico_encam_tot'] > 0) & 
                    (ttable_sm_step0['psico_consul_tot'] <= 10), 'adherent_tds_psico'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade MODERADA COM prejuízo') & 
                    (ttable_sm_step0['psico_encam_tot'] > 0) & 
                    (ttable_sm_step0['psico_consul_tot'] <= 10), 'adherent_tds_psico'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade GRAVE') & 
                    (ttable_sm_step0['psico_encam_tot'] > 0) & 
                    (ttable_sm_step0['psico_consul_tot'] <= 10), 'adherent_tds_psico'] = 1
#DEPRESSAO
ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Depressão LEVE') &
                    (ttable_sm_step0['psico_encam_tot'] > 0) & 
                    (ttable_sm_step0['psico_consul_tot'] <= 10),'adherent_tds_psico'] = 0

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Depressão LEVE COM histórico de abuso/ disf.sexual') & 
                    (ttable_sm_step0['psico_encam_tot'] > 0) & 
                    (ttable_sm_step0['psico_consul_tot'] <= 10), 'adherent_tds_psico'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Depressão MODERADA SEM prejuízo') & 
                    (ttable_sm_step0['psico_encam_tot'] > 0) & 
                    (ttable_sm_step0['psico_consul_tot'] <= 10), 'adherent_tds_psico'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Depressão MODERADA COM prejuízo') & 
                    (ttable_sm_step0['psico_encam_tot'] > 0) & 
                    (ttable_sm_step0['psico_consul_tot'] <= 10), 'adherent_tds_psico'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Depressão GRAVE') & 
                    (ttable_sm_step0['psico_encam_tot'] > 0) & 
                    (ttable_sm_step0['psico_consul_tot'] <= 10), 'adherent_tds_psico'] = 1

#Misto
ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Misto LEVE (ansiedade e depressão)'), 'adherent_tds_psico'] = 1
ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Misto LEVE (ansiedade e depressão)') & 
                    (ttable_sm_step0['psico_encam_tot'] > 0) & 
                    (ttable_sm_step0['psico_consul_tot'] <= 10), 'adherent_tds_psico'] = 0

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Misto MODERADO (ansiedade e depressão) SEM prejuízo') & 
                        (ttable_sm_step0['psico_encam_tot'] > 0) & 
                        (ttable_sm_step0['psico_consul_tot'] <= 10), 'adherent_tds_psico'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Misto MODERADO (ansiedade e depressão) COM prejuízo') & 
                    (ttable_sm_step0['psico_encam_tot'] > 0) & 
                    (ttable_sm_step0['psico_consul_tot'] <= 10), 'adherent_tds_psico'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Misto GRAVE (ansiedade e depressão)') & 
                    (ttable_sm_step0['psico_encam_tot'] > 0) & 
                    (ttable_sm_step0['psico_consul_tot'] <= 10), 'adherent_tds_psico'] = 1
#Transtornos tipo 1 & 2

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Transtorno Tipo 1') &
                    (ttable_sm_step0['psico_encam_tot'] > 0) & 
                    (ttable_sm_step0['psico_consul_tot'] <= 10), 'adherent_tds_psico'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Transtorno Tipo 2') &
                    (ttable_sm_step0['psico_encam_tot'] > 0) & 
                    (ttable_sm_step0['psico_consul_tot'] <= 10), 'adherent_tds_psico'] = 1

In [133]:


ttable_sm_step0 = ttable_sm_step0.merge(ttable_sm_step0.groupby(['member_internal_code', 'program_name'])['psiqui_qt_encaminhamentos'].sum().rename('psiqui_encam_tot'),
                                                            how = 'inner',
                                                            left_on = ['member_internal_code', 'program_name'], right_index = True)

ttable_sm_step0 = ttable_sm_step0.merge(ttable_sm_step0.groupby(['member_internal_code', 'program_name'])['psiqui_qt_consultas'].sum().rename('psiqui_qt_consultas_tot'),
                                                            how = 'inner',
                                                            left_on = ['member_internal_code', 'program_name'], right_index = True)

### 2.1.5. adjusting aggregated variables
 - comparecimentos totais a psico/psiqui, custos, etc

In [135]:
ttable_sm_step0['psico_comparecimento_pp_prod'] = ttable_sm_step0['psico_comparecimento_pp']*ttable_sm_step0['psico_qt_consultas']
ttable_sm_step0['psico_in_alice_net_pp_prod'] = ttable_sm_step0['psico_in_alice_net_pp']*ttable_sm_step0['psico_qt_consultas']

ttable_sm_step0['psiqui_is_presential_pp_prod'] = ttable_sm_step0['psiqui_is_presential_pp']*ttable_sm_step0['psiqui_qt_consultas']
ttable_sm_step0['psiqui_has_prescription_pp_prod'] = ttable_sm_step0['psiqui_has_prescription_pp']*ttable_sm_step0['psiqui_qt_consultas']


ttable_sm_step0 = ttable_sm_step0.merge(ttable_sm_step0.groupby(['member_internal_code', 'program_name'])['psico_comparecimento_pp_prod'].sum().rename('psico_comparecimento_pp_prod_tot'),
                                                            how = 'inner',
                                                            left_on = ['member_internal_code', 'program_name'], right_index = True)
ttable_sm_step0 = ttable_sm_step0.merge(ttable_sm_step0.groupby(['member_internal_code', 'program_name'])['psico_in_alice_net_pp_prod'].sum().rename('psico_in_alice_net_pp_prod_tot'),
                                                            how = 'inner',
                                                            left_on = ['member_internal_code', 'program_name'], right_index = True)

ttable_sm_step0 = ttable_sm_step0.merge(ttable_sm_step0.groupby(['member_internal_code', 'program_name'])['psiqui_is_presential_pp_prod'].sum().rename('psiqui_is_presential_pp_prod_tot'),
                                                            how = 'inner',
                                                            left_on = ['member_internal_code', 'program_name'], right_index = True)

ttable_sm_step0 = ttable_sm_step0.merge(ttable_sm_step0.groupby(['member_internal_code', 'program_name'])['psiqui_has_prescription_pp_prod'].sum().rename('psiqui_has_prescription_pp_prod_tot'),
                                                            how = 'inner',
                                                            left_on = ['member_internal_code', 'program_name'], right_index = True)


ttable_sm_step0['psico_comparecimento_pp_step0'] = ttable_sm_step0['psico_comparecimento_pp_prod_tot'].div(ttable_sm_step0['psico_consul_tot'])
ttable_sm_step0['psico_in_alice_net_pp_step0'] =  ttable_sm_step0['psico_in_alice_net_pp_prod_tot'].div(ttable_sm_step0['psico_consul_tot'])
ttable_sm_step0['psiqui_is_presential_pp_step0'] = ttable_sm_step0['psiqui_is_presential_pp_prod_tot'].div(ttable_sm_step0['psiqui_qt_consultas_tot'])
ttable_sm_step0['psiqui_has_prescription_pp_step0'] =  ttable_sm_step0['psiqui_has_prescription_pp_prod_tot'].div(ttable_sm_step0['psiqui_qt_consultas_tot'])


#custos totais step one
ttable_sm_step0 = ttable_sm_step0.merge(ttable_sm_step0.groupby(['member_internal_code', 'program_name'])['custo_evento_consultas_psico'].sum().rename('custo_evento_consultas_psico_step0'),
                                                            how = 'inner',
                                                            left_on = ['member_internal_code', 'program_name'], right_index = True)

ttable_sm_step0 = ttable_sm_step0.merge(ttable_sm_step0.groupby(['member_internal_code', 'program_name'])['custo_evento_consultas_psiqui'].sum().rename('custo_evento_consultas_psiqui_step0'),
                                                            how = 'inner',
                                                            left_on = ['member_internal_code', 'program_name'], right_index = True)

ttable_sm_step0 = ttable_sm_step0.merge(ttable_sm_step0.groupby(['member_internal_code', 'program_name'])['care_cost_tot_consultas_psico'].sum().rename('care_cost_consultas_psico_step0'),
                                                            how = 'inner',
                                                            left_on = ['member_internal_code', 'program_name'], right_index = True)

ttable_sm_step0 = ttable_sm_step0.merge(ttable_sm_step0.groupby(['member_internal_code', 'program_name'])['care_cost_tot_consultas_psiqui'].sum().rename('care_cost_consultas_psiqui_step0'),
                                                            how = 'inner',
                                                            left_on = ['member_internal_code', 'program_name'], right_index = True)

#adherences max
ttable_sm_step0 = ttable_sm_step0.merge(ttable_sm_step0.groupby(['member_internal_code', 'program_name'])['adherent_tds_trilha'].max().rename('adherent_tds_trilha_step0'),
                                                            how = 'inner',
                                                            left_on =['member_internal_code', 'program_name'], right_index = True)

ttable_sm_step0 = ttable_sm_step0.merge(ttable_sm_step0.groupby(['member_internal_code', 'program_name'])['adherent_tds_psico'].max().rename('adherent_tds_psico_step0'),
                                                            how = 'inner',
                                                            left_on = ['member_internal_code', 'program_name'], right_index = True)
ttable_sm_step0 = ttable_sm_step0.merge(ttable_sm_step0.groupby(['member_internal_code', 'program_name'])['adherent_tds_gad_phq'].max().rename('adherent_tds_gad_phq_step0'),
                                                            how = 'inner',
                                                            left_on = ['member_internal_code', 'program_name'], right_index = True)

### 2.1.6 Skewing and cleaning step zero
    - keeping only the first mth (entry program)

In [136]:
sm_adherence_step_zero = ttable_sm_step0[ttable_sm_step0['month_ord_on_program']==1]
sm_adherence_step_zero = sm_adherence_step_zero[['member_internal_code',
                                                 'program_name',
                                                 'calendar_date',
                                                 'current_medico_gestor',
                                                 'cancel_step0',
                                                 'adherent_tds_trilha_step0',
                                                 'adherent_tds_psico_step0',
                                                 'adherent_tds_gad_phq_step0']]

sm_adherence_step_zero.rename(columns = {'calendar_date': 'program_est_entry_date'}, inplace = True)
sm_adherence_step_zero['step'] = 0

2.1.8. Adjusting for ppl that have more than one program
     - nao precisamos de aderencia encaminhamento se foi de um programa para outro

In [137]:
sm_adherence_step_zero['program_order'] = sm_adherence_step_zero.groupby('member_internal_code')['program_est_entry_date'].rank(method='first')
sm_adherence_step_zero.loc[(sm_adherence_step_zero['program_order'] > 1), 'adherent_tds_psico_step0'] = 1

In [138]:
sm_adherence_step_zero[sm_adherence_step_zero['cancel_step0']==0][['adherent_tds_trilha_step0',
                                                                    'adherent_tds_psico_step0',
                                                                    'adherent_tds_gad_phq_step0']].describe()

,adherent_tds_trilha_step0,adherent_tds_psico_step0,adherent_tds_gad_phq_step0
count,3770.000000,3770.000000,3770.000000
mean,0.748011,0.607958,0.566578
std,0.434213,0.488271,0.495613
min,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000
50%,1.000000,1.000000,1.000000
75%,1.000000,1.000000,1.000000
max,1.000000,1.000000,1.000000

### 2.2. Compliance in the step zero

Compliance em trilha

In [139]:

#compliance a trilha
ttable_sm_step0['compliance_member_trilha']=0

#Ansiedades
ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade LEVE') & 
                    ((ttable_sm_step0['trilha_psicoeduc_stat_mth'] == 'ACTIVE')|(ttable_sm_step0['trilha_psicoeduc_stat_mth'] == 'FINISHED')) & 
                    ((ttable_sm_step0['trilha_mindfulness_stat_mth'] == 'ACTIVE')|(ttable_sm_step0['trilha_mindfulness_stat_mth'] == 'FINISHED')) , 'compliance_member_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade LEVE COM histórico de abuso/ disf.sexual') & 
                    ((ttable_sm_step0['trilha_psicoeduc_stat_mth'] == 'ACTIVE')|(ttable_sm_step0['trilha_psicoeduc_stat_mth'] == 'FINISHED')) & 
                    ((ttable_sm_step0['trilha_mindfulness_stat_mth'] == 'ACTIVE')|(ttable_sm_step0['trilha_mindfulness_stat_mth'] == 'FINISHED')) , 'compliance_member_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade LEVE COM histórico de abuso/aborto') & 
                    ((ttable_sm_step0['trilha_psicoeduc_stat_mth'] == 'ACTIVE')|(ttable_sm_step0['trilha_psicoeduc_stat_mth'] == 'FINISHED')) & 
                    ((ttable_sm_step0['trilha_mindfulness_stat_mth'] == 'ACTIVE')|(ttable_sm_step0['trilha_mindfulness_stat_mth'] == 'FINISHED')), 'compliance_member_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade MODERADA SEM prejuízo') & 
                    ((ttable_sm_step0['trilha_psicoeduc_stat_mth'] == 'ACTIVE')|(ttable_sm_step0['trilha_psicoeduc_stat_mth'] == 'FINISHED')), 'compliance_member_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade MODERADA COM prejuízo') & 
                    ((ttable_sm_step0['trilha_psicoeduc_stat_mth'] == 'ACTIVE')|(ttable_sm_step0['trilha_psicoeduc_stat_mth'] == 'FINISHED')), 'compliance_member_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade GRAVE') & 
                    ((ttable_sm_step0['trilha_psicoeduc_stat_mth'] == 'ACTIVE')|(ttable_sm_step0['trilha_psicoeduc_stat_mth'] == 'FINISHED')), 'compliance_member_trilha'] = 1

#DEPRESSAO
ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Depressão LEVE') & 
                    ((ttable_sm_step0['trilha_mindfulness_stat_mth'] == 'ACTIVE')|(ttable_sm_step0['trilha_mindfulness_stat_mth'] == 'FINISHED')) , 'compliance_member_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Depressão LEVE COM histórico de abuso/ disf.sexual'), 'compliance_member_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Depressão MODERADA SEM prejuízo'), 'compliance_member_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Depressão MODERADA COM prejuízo'), 'compliance_member_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Depressão GRAVE'), 'compliance_member_trilha'] = 1


#Misto
ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Misto LEVE (ansiedade e depressão)'), 'compliance_member_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Misto MODERADO (ansiedade e depressão) SEM prejuízo'), 'compliance_member_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Misto MODERADO (ansiedade e depressão) COM prejuízo'), 'compliance_member_trilha'] = 1

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Misto GRAVE (ansiedade e depressão)'), 'compliance_member_trilha'] = 1


#Transtornos tipo 1 & 2
ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Transtorno Tipo 1'), 'compliance_member_trilha'] = 1
ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Transtorno Tipo 2'), 'compliance_member_trilha'] = 1

Compliance em gad-phq (mesmo que aderencia)

In [140]:
#aderente ao gad
ttable_sm_step0['compliance_member_gad_phq']=0

ttable_sm_step0.loc[ttable_sm_step0['ult_gad7_valor'].notna(), 'compliance_member_gad_phq'] = 1
ttable_sm_step0.loc[ttable_sm_step0['ult_phq9_valor'].notna(), 'compliance_member_gad_phq'] = 1

Compliance em psico & psiqui (possibilidade de parcial)

In [141]:
# aderente a psicologo
ttable_sm_step0['compliance_member_psico']=0
                                                            
#Ansiedades
ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade LEVE'), 'compliance_member_psico'] = 1
ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade LEVE') &
                    (ttable_sm_step0['psico_consul_tot']>0), 'compliance_member_psico'] = ttable_sm_step0['psico_comparecimento_pp_step0']


ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade LEVE COM histórico de abuso/ disf.sexual') & 
                        (ttable_sm_step0['psico_consul_tot']>0), 'compliance_member_psico'] = ttable_sm_step0['psico_comparecimento_pp_step0']

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade LEVE COM histórico de abuso/aborto') & 
                        (ttable_sm_step0['psico_consul_tot']>0), 'compliance_member_psico'] = ttable_sm_step0['psico_comparecimento_pp_step0']

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade MODERADA SEM prejuízo') & 
                        (ttable_sm_step0['psico_consul_tot']>0), 'compliance_member_psico'] = ttable_sm_step0['psico_comparecimento_pp_step0']

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade MODERADA COM prejuízo') & 
                        (ttable_sm_step0['psico_consul_tot']>0), 'compliance_member_psico'] = ttable_sm_step0['psico_comparecimento_pp_step0']

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Ansiedade GRAVE') & 
                        (ttable_sm_step0['psico_consul_tot']>0), 'compliance_member_psico'] = ttable_sm_step0['psico_comparecimento_pp_step0']
#DEPRESSAO
ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Depressão LEVE'), 'compliance_member_psico'] = 1
ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Depressão LEVE') &
                    (ttable_sm_step0['psico_consul_tot']>0), 'compliance_member_psico'] = ttable_sm_step0['psico_comparecimento_pp_step0']


ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Depressão LEVE COM histórico de abuso/ disf.sexual') & 
                    (ttable_sm_step0['psico_consul_tot']>0),  'compliance_member_psico'] = ttable_sm_step0['psico_comparecimento_pp_step0']

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Depressão MODERADA SEM prejuízo') & 
                     (ttable_sm_step0['psico_consul_tot']>0),'compliance_member_psico'] = ttable_sm_step0['psico_comparecimento_pp_step0']

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Depressão MODERADA COM prejuízo') & 
                     (ttable_sm_step0['psico_consul_tot']>0), 'compliance_member_psico'] = ttable_sm_step0['psico_comparecimento_pp_step0']

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Depressão GRAVE') & 
                     (ttable_sm_step0['psico_consul_tot']>0), 'compliance_member_psico'] = ttable_sm_step0['psico_comparecimento_pp_step0']

#Misto
ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Misto LEVE (ansiedade e depressão)'), 'compliance_member_psico'] = 1
ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Misto LEVE (ansiedade e depressão)') &
                    (ttable_sm_step0['psico_consul_tot']>0), 'compliance_member_psico'] = ttable_sm_step0['psico_comparecimento_pp_step0']


ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Misto MODERADO (ansiedade e depressão) SEM prejuízo') & 
                     (ttable_sm_step0['psico_consul_tot']>0), 'compliance_member_psico'] = ttable_sm_step0['psico_comparecimento_pp_step0']


ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Misto MODERADO (ansiedade e depressão) COM prejuízo') & 
                    (ttable_sm_step0['psico_consul_tot']>0), 'compliance_member_psico'] = ttable_sm_step0['psico_comparecimento_pp_step0']


ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Misto GRAVE (ansiedade e depressão)') & 
                    (ttable_sm_step0['psico_consul_tot']>0),  'compliance_member_psico'] = ttable_sm_step0['psico_comparecimento_pp_step0']

#Transtornos tipo 1 & 2

ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Transtorno Tipo 1') &
                    (ttable_sm_step0['psico_consul_tot']>0),  'compliance_member_psico'] = ttable_sm_step0['psico_comparecimento_pp_step0']


ttable_sm_step0.loc[(ttable_sm_step0['program_name'] == 'Transtorno Tipo 2') &
                    (ttable_sm_step0['psico_consul_tot']>0), 'compliance_member_psico'] = ttable_sm_step0['psico_comparecimento_pp_step0']

Compliance em psiquiatria (sempre =1, pois não temos como checar no-show, sabemos somente se a pessoa vai - e como o psiquiatra é facultativo para o TdS se n_consultas = 0  ou nan pode ser que membro nao foi enviado ao psiquiatra)

In [142]:
# aderente a psiquiatria
ttable_sm_step0['compliance_member_psiqui']=1

Compliance em medicine (mesmo que aderencia do TdS)

### 2.2.2. Adjusting Variables for compliance

In [143]:

#compliance max
ttable_sm_step0 = ttable_sm_step0.merge(ttable_sm_step0.groupby(['member_internal_code', 'program_name'])['compliance_member_trilha'].max().rename('compliance_member_trilha_step0'),
                                                            how = 'inner',
                                                            left_on =['member_internal_code', 'program_name'], right_index = True)

ttable_sm_step0 = ttable_sm_step0.merge(ttable_sm_step0.groupby(['member_internal_code', 'program_name'])['compliance_member_psico'].max().rename('compliance_member_psico_step0'),
                                                            how = 'inner',
                                                            left_on = ['member_internal_code', 'program_name'], right_index = True)
ttable_sm_step0 = ttable_sm_step0.merge(ttable_sm_step0.groupby(['member_internal_code', 'program_name'])['compliance_member_gad_phq'].max().rename('compliance_member_gad_phq_step0'),
                                                            how = 'inner',
                                                            left_on = ['member_internal_code', 'program_name'], right_index = True)

ttable_sm_step0 = ttable_sm_step0.merge(ttable_sm_step0.groupby(['member_internal_code', 'program_name'])['compliance_member_psiqui'].max().rename('compliance_member_psiqui_step0'),
                                                            how = 'inner',
                                                            left_on = ['member_internal_code', 'program_name'], right_index = True)         
  

sm_compliance_step_zero = ttable_sm_step0[ttable_sm_step0['month_ord_on_program']==1]
sm_compliance_step_zero = sm_compliance_step_zero[['member_internal_code',
                                                    'program_name',
                                                    'calendar_date',
                                                    'cancel_step0',
                                                    'compliance_member_trilha_step0',
                                                    'compliance_member_psico_step0',
                                                    'compliance_member_gad_phq_step0',
                                                    'compliance_member_psiqui_step0']]

sm_compliance_step_zero.rename(columns = {'calendar_date': 'program_est_entry_date'}, inplace = True)
sm_compliance_step_zero['step'] = 0

In [144]:
sm_compliance_step_zero[sm_compliance_step_zero['cancel_step0']==0][[
                                                    'compliance_member_trilha_step0',
                                                    'compliance_member_psico_step0',
                                                    'compliance_member_gad_phq_step0',
                                                    'compliance_member_psiqui_step0']].describe()

,compliance_member_trilha_step0,compliance_member_psico_step0,compliance_member_gad_phq_step0,compliance_member_psiqui_step0
count,3770.000000,3770.000000,3770.000000,3770.0
mean,0.746419,0.392971,0.566578,1.0
std,0.435118,0.474632,0.495613,0.0
min,0.000000,0.000000,0.000000,1.0
25%,0.000000,0.000000,0.000000,1.0
50%,1.000000,0.000000,1.000000,1.0
75%,1.000000,1.000000,1.000000,1.0
max,1.000000,1.000000,1.000000,1.0